services:
  mysql:
    image: mysql:8.4
    container_name: server-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your-super-secure-password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: your-second-super-secure-password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - web

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: server-pma
    restart: always
    environment:
      PMA_HOST: mysql
    labels:
      caddy: "pma.{your-domain-name}"
      caddy.reverse_proxy: "{{upstreams 80}}"
    depends_on:
      - mysql
    networks:
      - web

volumes:
  mysql-data:
    driver: local

networks:
  web:
    name: web
    external: true