name: Cleanup Old Apps

on:
  delete:
  workflow_dispatch:

jobs:
  call-deploy:
    uses: tonsoo/deployer/.github/workflows/cleanup.yml@main
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_USER: ${{ secrets.SSH_USER }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}