services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: "{{APP_NAME}}-webapp-{{BRANCH_NAME}}"
    volumes:
      - .:/app
    labels:
      caddy: "{{DOMAIN}}"
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - web

networks:
  web:
    name: web
    external: true