name: Cleanup
on:
  workflow_call:
    secrets:
      SSH_HOST:
        required: true
        description: "Your ssh host for server connection"
      SSH_PRIVATE_KEY:
        required: true
        description: "Your ssh private key for accessing server"
      SSH_USER:
        required: true
        description: "Your ssh username for server connection"
      DEPLOY_PATH:
        required: true
        description: "Your server absolute deploy path, without forwas slash, such as '/var/www/my-app'"

permissions:
  contents: read

jobs:
  cleanup:
    name: Cleanup deleted branch
    runs-on: ubuntu-latest
    steps:
      - name: Set env vars from deleted ref
        id: set-env-vars
        run: |
          BRANCH_NAME=$(echo "${{ github.event.ref }}" | tr '/' '-')

          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "DEPLOY_DIR=${{ secrets.DEPLOY_PATH }}/$BRANCH_NAME" >> $GITHUB_ENV

      - name: Setup ssh
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add ssh host
        run: |
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Delete deployment folder on server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF

          echo "Deleting deployment for branch: ${{ env.BRANCH_NAME }}"
          DEPLOY_DIR="${{ env.DEPLOY_DIR }}"

          if [ -d "$DEPLOY_DIR" ]; then
            cd "$DEPLOY_DIR"
            docker compose down --volumes --remove-orphans

            cd ..
            echo "Removing deployment directory..."
            rm -rf "$DEPLOY_DIR"
          fi
          EOF